DIT/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BLL;
using Models;
using System.Web.Mvc;
using BLL.Attendance;
using System.Text;
using System.Configuration;
using System.IO;
using Newtonsoft.Json;
using Models.AttendanceDetails;

namespace DIT.Controllers
{
    public class AttendanceController : Controller
    {
      private readonly IAttendanceBLL _attendBll;
      private readonly string UploadFolder = ConfigurationManager.AppSettings["TemplateDocumentsPath"];

        // strings to generate file name
        private readonly string PdfFileNameFormat = "InvigilatorDairy{0}.pdf";
        private readonly string ExcelFileNameFormat = "InvigilatorDairy{0}.pdf";
        // GET: Attendance

        public AttendanceController()
        {
            _attendBll = new AttendanceBLL();
        }
        public ActionResult Index()
        {
            return View();
        }



        //public ActionResult AttendanceDet()
        //{
           
        //    return View();
        //}


        public ActionResult AttendanceDet()
        {
            AtendanceDet model = new AtendanceDet();
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
            model.divisionList = _attendBll.GetDivisionListBLL();
            model.ExamCentrList = _attendBll.GetCenterListBLL();
            return View(model);
        }

        [HttpPost]
        public JsonResult AttendanceDetUpload(AtendanceDet model)
        {
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
            // var res = _attendBll.ExamAttendanceUploadBLL(model);
            var res = 2;
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult getAttendanceDet(int divId)
        {
            AtendanceDet model = new AtendanceDet();
            StringBuilder sb = new StringBuilder();
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
            // model.divId = Convert.ToInt16(divId);
           // var res = 0;
           var res = _attendBll.getAttendanceDetBLL(divId);
           // sb.Append("< tr >< td > " ' + slNo + " </ td >< td > " + attentdance.Day + " </ td >< td > " + dateFormat(new Date(parseInt((attentdance.ECT_ExamDate).match(/\d+/)[0]))) + " </ td >< td > " + attentdance.padStart + " </ td >< td > " + attentdance.Day+ " </ td >< td > " + attentdance.Day + " </ td >< td > " + attentdance.Day + " </ td ></ tr > ";")
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ModifyAttendanceDtls(int divId)
        {
            AtendanceDet model = new AtendanceDet();
          
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
           
            var res = _attendBll.getModifyAttendanceDetBLL(divId);
            // sb.Append("< tr >< td > " ' + slNo + " </ td >< td > " + attentdance.Day + " </ td >< td > " + dateFormat(new Date(parseInt((attentdance.ECT_ExamDate).match(/\d+/)[0]))) + " </ td >< td > " + attentdance.padStart + " </ td >< td > " + attentdance.Day+ " </ td >< td > " + attentdance.Day + " </ td >< td > " + attentdance.Day + " </ td ></ tr > ";")
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetDtlsByTraineRollNumber(int rollNo)
        {
            AtendanceDet model = new AtendanceDet();
           
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
           
            var res = _attendBll.getTraineeDtlsByRollNoBLL(rollNo);
            // sb.Append("< tr >< td > " ' + slNo + " </ td >< td > " + attentdance.Day + " </ td >< td > " + dateFormat(new Date(parseInt((attentdance.ECT_ExamDate).match(/\d+/)[0]))) + " </ td >< td > " + attentdance.padStart + " </ td >< td > " + attentdance.Day+ " </ td >< td > " + attentdance.Day + " </ td >< td > " + attentdance.Day + " </ td ></ tr > ";")
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult saveExamattendanceDetails(FormCollection formCollection)
        {
            // get the files from view
            HttpFileCollectionBase files = Request.Files;
            List<AtendanceDet> models = new List<AtendanceDet>();

            // get all the row data
            foreach(var key in formCollection.AllKeys)
            {
                //Deserialize JSON to class
                AtendanceDet model = JsonConvert.DeserializeObject<AtendanceDet>(formCollection[key]);
                model.User_Id = Convert.ToInt32(Session["LoginId"]);
                for (int index =0; index < files.Count; index++)
                {
                    // assign file to be uploaded
                    if(model.attendSavePath == files[index].FileName)
                    {
                        model.UploadPdf = files[index];
                    }
                    else if (model.attendExcelPath == files[index].FileName)
                    {
                        model.UploadXcel = files[index];
                    }
                }
                models.Add(model);
            }
           
            var res = _attendBll.CreateAttendanceDetailsBLL(models);
            return Json(res, JsonRequestBehavior.AllowGet);

        }
		
		  [HttpPost]
        public JsonResult UpdateExamattendanceDetails(FormCollection formCollection)
        {
            // get the files from view
            HttpFileCollectionBase files = Request.Files;
            List<AtendanceDet> models = new List<AtendanceDet>();

            //AtendanceDet models = new AtendanceDet();


            // get all the row data
            foreach (var key in formCollection.AllKeys)
            {
                //Deserialize JSON to class
                AtendanceDet model = JsonConvert.DeserializeObject<AtendanceDet>(formCollection[key]);
                model.User_Id = Convert.ToInt32(Session["LoginId"]);
                for (int index = 0; index < files.Count; index++)
                {
                    // assign file to be uploaded
                    if (model.attendSavePath == files[index].FileName)
                    {
                        model.UploadPdf = files[index];
                    }
                    else if (model.attendExcelPath == files[index].FileName)
                    {
                        model.UploadXcel = files[index];
                    }
                }
                models.Add(model);
            }

            var res = _attendBll.UpdateAttendanceDetailsBLL(models);
            //  var res = _attendBll.ExamAttendanceUploadBLL(models);
            return Json(res, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ModifiyExamAttendanceDet()
        {
            AtendanceDet model = new AtendanceDet();
            model.User_Id = Convert.ToInt32(Session["LoginId"]);
            model.divisionList = _attendBll.GetDivisionListBLL();
            model.ExamCentrList = _attendBll.GetCenterListBLL();
            return View(model);
            
        }

        [HttpGet]
        public ActionResult GetExamAttendanceDtls()
        {
            AtendanceDet model = new AtendanceDet();
            model.LoginRoleList = _attendBll.GetLoginRoleListBLL();
            model.login_id = Convert.ToInt32(Session["LoginId"]);
            model.AttendanceDetList = _attendBll.getAttendanceDtlsBLL(model);
            
            return View(model);

        }

        [HttpPost]
        public JsonResult AttendanceDtls(int ID)
        {
            AtendanceDet model = new AtendanceDet();
            model.LoginRoleList = _attendBll.GetLoginRoleListBLL();
            model.attenId = ID;
            var List = _attendBll.ViewAttendanceDtlsBLL(model);

            return Json(List, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public JsonResult AttendanceApproveStatus(int Id, int Status, int Loginid)//loginid => roleID
        {
            AtendanceDet model = new AtendanceDet();
            model.login_id = Convert.ToInt32(Session["LoginId"]);
            model.attenId = Id;
            model.status_id = Status;
            model.RoleId = Loginid;
            int? updateemployee = this._attendBll.ApproveStatusBLL(model);
            string res = updateemployee.ToString();
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LoginBasedExamAttendanceList()
        {
            AtendanceDet modal = new AtendanceDet();
            modal.LoginRoleList = _attendBll.GetLoginRoleListBLL();
            int loginId = Convert.ToInt32(Session["LoginId"]);
            //modal.RoleId = Convert.ToInt32(Session["LoginId"]);
            modal.RoleId = loginId;
            //modal.user_role = Session["UserRole"].ToString();
            List<AtendanceDet> list = _attendBll.GetAttendanceDtlsByLoginIdBLL(modal).ToList();
            modal.attendanceList = list;
            return View(modal);
        }

        [HttpPost]
      //  public JsonResult AttendBackToCW(int Id, int Status, int Loginid, string comments, int StatusforCW)
             public JsonResult AttendBackToCW(string Id, string Status, string Loginid, string comments, string StatusforCW)
        {
            AtendanceDet model = new AtendanceDet();
            model.login_id = Convert.ToInt32(Session["LoginId"]);
            model.attenId = Convert.ToInt32(Id);
            model.exam_notif_status_id = Convert.ToInt32(Status);
            model.RoleId = Convert.ToInt32(Loginid);
            model.updatestatusCW = Convert.ToInt32(StatusforCW);
            model.comments = comments;
            string updateemployee = this._attendBll.UpdateCWStatusAttendanceBLL(model);
            string res = updateemployee.ToString();
            return Json(res, JsonRequestBehavior.AllowGet);
        }


    }
}

DIT/Views/Attendance/GetExamAttendanceDtls.cshtml
@model Models.AttendanceDetails.AtendanceDet
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Content/frontend/js/bootstrap.js"></script>
<script src="~/Scripts/bootbox.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/Scripts/bootbox.locales.min.js"></script>
<script src="~/Content/frontend/js/jquery-ui.min.js"></script>
<link rel="stylesheet" href="~/Content/css/jquery-ui.min.css" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetExamAttendanceDtls</title>
</head>
<body>
    <div>
        <br /><br /><br />
        <input type="hidden" value="@Model.attendSavePath" name="attendSavePath" id="test"/>
        <table class="table table-bordered table-hover text-center " style="color:white; background-color:aliceblue" id="tblGrid">
            <thead>
                <tr class="text-center" style="color:black">
                    <th>SlNo.</th>
                    <th>Exam Day</th>

                    <th>Block Number</th>
                    <th>Trainee Roll No.</th>
                    <th> Status</th>

                    <th style="display:none">InvigilatorDairy</th>
                    <th style="display:none">ExcelInvigilatorDairy</th>
                    <th>Send To</th>
                    <th>Send</th>

                    <th>Action</th>
                </tr>
            </thead>
            <tbody style="color:Black;">
                @foreach (var item in Model.AttendanceDetList)
                {
                <tr>
                    @*<td>@(sno++)</td>*@
                    <td align="center" class="noExport">@item.attenId</td>
                    <td>@item.Day</td>
                    <td>@item.BlockNo</td>
                    <td>@item.Trainee_Roll_Num</td>
                    <td>@item.status_desc</td>
                    <td style="display:none" id="filename">@item.attendSavePath</td>
                    <td style="display:none">@item.attendExcelPath</td>

                    <td>
                        @if (item.status_desc.ToString().Equals("Ready to Send for Approval"))
                        {
                            @Html.DropDownListFor(model => model.RoleId, new SelectList(Model.LoginRoleList, "Value", "Text"), new { @class = "form-control select2", @onchange = "GetSelectedValue(this.value)" })
                            @Html.ValidationMessageFor(x => x.RoleId, "", new { @class = "text-danger" })

                        }
                        else
                        {
                            @Html.DropDownListFor(model => model.RoleId, new SelectList(Model.LoginRoleList, "Value", "Text"), new { @class = "form-control select2", @onchange = "GetSelectedValue(this.value)", @id = "Sectionlsts", disabled = "disabled" })
                            @Html.ValidationMessageFor(x => x.RoleId, "", new { @class = "text-danger" })
                        }


                    </td>

                    <td>
                        @*<a class=" btn btn-primary" onclick="viewDetails(@item.Exam_Notif_Id)" data-toggle="modal" data-target="#myModal">View</a>*@
                        @if (item.status_desc.ToString().Equals("Approved - Pending for Publish"))
                        {
                            <a class=" btn btn-primary" id="sendBtn" onclick="SendattndDetails(@item.attenId,@item.status_id)">Send</a>
                        }
                        else
                        {
                            <a class=" btn btn-primary" id="sendBtn" onclick="SendattndDetails(@item.attenId,@item.status_id)">Send</a>
                        }

                    </td>
                    @*<td>

            <div>
                <a href=" + pdfUrlPath + " target='_blank'>View</a>
            </div>
        </td>*@
                    <td>
                        @if (item.StatusId == 1)
                        {
                            <a class=" btn btn-primary" href='@Url.Action("AttendanceDet", "Attendance", new { AttendanceId = item.attenId})'>Edit</a>
                        }

                        @if (item.StatusId == 2)
                        {
                            <a class="btn btn-primary RateAnalysis" id="sendBtn" href='javascript:;' @*onclick="ViewDetails(@item.attenId,@item.StatusId)"*@>View</a>
                        }

                        <a class="btn btn-primary" id="sendBtn" onclick="GetCommentFileDetails(@item.attenId)">View</a>
                    </td>



                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

<div class="modal fade" id="HistoryRemarksCommentsModal" role="dialog">
    <div class="modal-dialog modal-xl" style="width: 60%; margin: 30px auto; padding: 2px;">
        <div class="modal-content" style="padding:15px;">
            <div class="modal-header">
                <h4 class="modal-title">Remark Details</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <br />
            <div>
                <input type="button" value="ViewAttendanceUploadFile" class="btn btn-primary" onclick="GetClientReport1()" style="margin-left:15px; width:250px;" id="btnFileView" />
            </div>
            <br />

            <table class="table table-striped table-hover text-center shadow clswidth" id="GetCommentRemarksDetails" style="width:100% !important" border="1" align="center"></table>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" style="width: 20%;">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#tblGrid').DataTable({

        });
    });

    var RoleId = '';
    function GetSelectedValue(ID1) {
        RoleId = ID1;
    }

    function ViewDetails(id, status) {
        
        $.ajax({
            type: "POST",
            url: "/Notification/PublishNotification",
            dataType: 'json',
            data: {
                Id: id,
                Status: status,
                //Loginid: RoleId,
            },

            success: function (response) {
                
                if (response == "Saved") {
                    //$('#sendBtn').attr("disabled", "disabled");
                    var _msg = "Published Success  fully Successfully";
                    //bootbox.alert(_msg);
                    bootbox.alert({ message: _msg, callback: function () { window.location.href = window.location.href; } });
                }
                else {
                    var _msg = "Fail to send";
                    bootbox.alert(_msg);
                }
            }, error: function (e) {
                var _msg = "Something went wrong.";
                bootbox.alert(_msg);
                $("#preloder, .loader").hide();
            }
        });
    }
    function SendattndDetails(id, status) {
        
        $.ajax({
            type: "POST",
            url: "/Attendance/AttendanceApproveStatus",
            dataType: 'json',
            data: {
                Id: id,
                Status: status,
                Loginid: RoleId,
            },

            success: function (response) {

                if (response == 1) {
                    //$('#sendBtn').attr("disabled", "disabled");
                    var _msg = "Sent Successfully";
                    bootbox.alert({ message: _msg, callback: function () { window.location.href = window.location.href; } });
                }
                else {
                    var _msg = "Fail to send";
                    bootbox.alert(_msg);
                }
            }, error: function (e) {
                var _msg = "Something went wrong.";
                bootbox.alert(_msg);
                $("#preloder, .loader").hide();
            }
        });
    }

    function GetCommentFileDetails(id) {

        $('#HistoryRemarksCommentsModal').modal('show');
        //NotifId = id;
        
        $.ajax({
            type: "Post",
            url: "/Notification/GetCommentFileDetails",
            data: { NotificationId: id },
            success: function (data) {
                var t = $('#GetCommentRemarksDetails').DataTable({
                    data: data,
                    destroy: true,
                    columns: [
                        { 'data': 'createdatetime', 'title': 'Sl No', 'className': 'text-center' },
                        { 'data': 'createdatetime', 'title': 'Date', 'className': 'text-left' },
                        { 'data': 'Exam_Notif_Number', 'title': 'Notification Number', 'className': 'text-left' },
                        { 'data': 'comments', 'title': 'Descriptioon', 'className': 'text-left' },
                        { 'data': 'user_name', 'title': 'Designation', 'className': 'text-left' },

                    ]
                });
                t.on('order.dt search.dt', function () {
                    t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();
               // NotifId = data[0].Exam_Notif_Number;
            }
        });
    }

    function GetClientReport1() {
        var pdf_file = $('#test').val();
        

        var urlPath = "../../Content//Uploads//" + file1 + " ";
        window.open(urlPath, '_blank');
        
    }


</script>

<script type="text/javascript">
   @*// var selectedTab = '@Model.selectTab';*@
    var pdf_file = $('#test').text();
    var file_path = '';
    $("body").on("click", "#tblGrid .RateAnalysis", function () {
        var $tdfile_path = row.find("td:nth-child(6)");
        file_path = $tdfile_path.text().trim();
    });
</script>

DIT/Views/Attendance/InvigilatorDairyTemplateCreation.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InvigilatorDairyTemplateCreation</title>
</head>

<br />
<br />
<br />

<body>

    <div class="container" style="background-color:white;box-shadow: 0 2px 4px rgba(0,0,0,0.6);margin-top:20px; padding:20px;">

        <h3 style="text-align:center">InvigilatorDairyTemplate</h3>
        <br/>
        <br/>
        <br/>
        <div class="form-group row">
            <div class="col-lg-12 col-md-12">
                <div class="col-md-6 col-lg-offset-5">
                  
                    <input type="submit" id="CreateDairy" value="CreateAttendanceDairy" class="btn btn-success" style="margin-left:15px;width:250px" />
                </div>
            </div>
        </div>
    </div>
</body>
</html>

<script>
    $("#CreateDairy").click(function (e) {
        
        $.ajax({
            type: 'POST',
            url: '/Attendance/InvigilatorDairyTmpl',
            
            contentType: false,
            processData: false,
            cache: false,
            async: false,
            success: function (result) {
                if (result != "Failed") {
                    bootbox.alert("Saved Sucessfully.");
                  
                }
                else {
                    bootbox.alert("Error Adding Data into Grid")
                }
            },
            error: function () {
                bootbox.alert("Error");
            }
        });
        
    });
</script>

DIT/Views/Attendance/OMREntry.cshtml
@model Models.OMRSheetDetails
@{
    ViewBag.Title = "ExamCalendarMaster";
}

<link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Content/frontend/js/bootstrap.js"></script>
<script src="~/Scripts/bootbox.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
<script src="~/Scripts/bootbox.locales.min.js"></script>
<script src="~/Content/frontend/js/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

<style>
    button {
        background-color: #5A8CD3;
        color: white;
    }

    button {
        background-color: #5A8CD3;
        color: white;
    }

    .content-box-gray .content {
        overflow: hidden;
        padding: 10px;
        font-size: 15px;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
        border: 1px solid gray;
        color: #3385FF;
    }

    .content-box-gray .title {
        height: 50px;
        line-height: 30px;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
        /*background: #5A8CD3;*/
        font-size: 18px;
        font-weight: bold;
        font-family: verdana;
        display: block;
        color: white;
        display: block;
        padding: 10px;
        border: 1px solid gray;
        border-bottom: none;
    }
</style>
<br /><br /><br />
<h4>
    <ul class="nav nav-tabs">
        <li>
            <a href="#tab_1" id="tab1" data-toggle="tab">OMR Sheet No. Details</a>
        </li>
        <li>
            <a href="#tab_2" id="tab2" data-toggle="tab">Modify OMR Sheet No. Details</a>
        </li>
    </ul>
</h4>
<div class="tab-content">
    <div class="tab-pane fade" id="tab_1">
        <div class="container" style="background-color:white;box-shadow: 0 2px 4px rgba(0,0,0,0.6);margin-top:20px; padding:20px; width: 1350px;">
            <div class="row">
                <div class="col-lg-12">
                    <h3 style="text-align:center">Capture of OMR Sheet</h3>
                    <br /><br />
                    <div class="form-group row">
                        <div class="col-lg-6 col-md-6">
                            <div class="col-md-6">
                                <label for="txtAgencyRegnNo">Division<span style="color:red"> *</span></label>
                            </div>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.division_Id, new SelectList(Model.Division_List, "Value", "Text"), new { @class = "form-control select2", @onchange = "GetDivisionBasedData(this.value)" })
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="col-md-6">
                                <label for="txtAgencyRegnNo">Exam Center<span style="color:red"> *</span></label>
                            </div>
                            <div class="col-md-6">
                                @Html.DropDownListFor(model => model.Exam_Cntr_Id, new SelectList(Model.Exam_Centr_List, "Value", "Text"), new { @class = "form-control select2" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-6 col-md-6">
                            <div class="col-md-6">
                                <label for="txtAgencyRegnNo">Exam Date<span style="color:red"> *</span></label>
                            </div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Exam_Date, "{0:dd/MM/yyyy}", new { @class = "form-control", autocomplete = "off", @type = "Date", style = " background-position:right; background-size:30px; " })
                            </div>
                        </div>
                    </div>
                    <br />
                    <br />
                    <table class="table table-bordered table-hover" id="OMR_Entry_Grid_table">
                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>DATE</th>
                                <th>DAY </th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Trade Year</th>
                                <th>Subject</th>
                                <th>Room/Block  No.</th>
                                <th>Invigilator Diary (Scanned Copy)</th>
                                <th>Invigilator Diary (Editable Copy)</th>
                            </tr>
                        </thead>
                        <tbody id="Add_OMREntryGrid">
                            @if (Model.OMRSheetDetailsList != null)
                            {
                                foreach (var item in Model.OMRSheetDetailsList)
                                {
                                        <tr>
                                            <td>@item.Exam_Date</td>
                                            <td>@item.Exam_Date</td>
                                            <td>@item.Exam_Start_date</td>
                                            <td>@item.Exam_End_date</td>
                                            <td>@item.TradeYr</td>
                                            <td>@item.Subject</td>
                                            <td>@Html.TextBox("Room" + item.RoomNo, item.RoomNo))</td>
                                        </tr>
                                }
                            }
                        </tbody>
                    </table>
                    <br />
                    <div class="form-group row">
                        <div class="col-lg-12 col-md-12">
                            <div class="col-md-6 col-lg-offset-3">
                                <input type="button" value="Clear" class="btn btn-success" style="margin-left:15px; width:250px;" id="btnClearOMREntry" />
                                <input type="button" id="btnSaveOMREntry" value="Save" class="btn btn-success" style="margin-left:15px;width:250px" />
                            </div>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
        </div>
        <br /><br />
    </div>
</div>
<script type="text/javascript">
    function GetDivisionBasedData(divId) {
        $.ajax({
            type: "Post",
            url: '/Attendance/GetOMREntry',
            data: { divId: divId },
            success: function (data) {
                if (data.length > 0) {
                    $("#Add_OMREntryGrid").empty();
                    var slNo = 1;
                    $.each(data, function (id, attentdance) {
                        var markup = "<tr><td>" + slNo + "</td><td>" + attentdance.Day + "</td><td>" + attentdance.EExam_Date + "</td><td id = 'startTime'>" + attentdance.Exam_Start_date + "</td><td>" + attentdance.Exam_End_date + "</td><td>" + attentdance.TradeYr + "</td><td>" + attentdance.Subject + "</td><td style='width:30%;'>" + "<input type='text' id='txtName'  value=''>" + "</td><td>" + "<input class= 'btn btn-success' style='align:center; margin:10px;' type='file' id='UploadDocsFile' onchange = 'Upload()'>" + "</td><td>" + "<input class= 'btn btn-success' style='align:center; margin:10px;' type='file' id='UploadExcelFile' onchange = 'ExcelUpload()'>" + "</td></tr>";
                        $("#Add_OMREntryGrid").append(markup);
                        slNo++;
                    });
                }
            }
        });
    }
    </script>