DIT/Controllers/NotificationController.cs
using BLL.ExamNotification;
using Models;
using Models.ExamNotification;
using System;
using Models.ExamCenterMap;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Text;
using Spire.Doc;
using Spire.Doc.Documents;
using System.Web.UI.WebControls;
using System.Net.Mail;

using Table = Spire.Doc.Table;
using TableRow = Spire.Doc.TableRow;
using TableCell = Spire.Doc.TableCell;
using Paragraph = Spire.Doc.Documents.Paragraph;
using Microsoft.Office.Interop;
//using Microsoft.Office.Interop.Word;
using System.Text.RegularExpressions;
using System.Data;
using Spire.Pdf;
using System.Threading;
using Spire.Pdf.HtmlConverter;
using Spire.Pdf.Graphics;
using BLL;

using Org.BouncyCastle.Security;
using Org.BouncyCastle.X509;
//using X509Certificate = Org.BouncyCastle.X509.X509Certificate;
using System.Security.Cryptography.X509Certificates;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.security;
using iTextSharp.text.pdf.parser;
using Spire.Pdf.Widget;
using System.Drawing;
using Spire.Pdf.AutomaticFields;
using System.Web.Configuration;
using System.Net.Security;
using System.Net;
using X509Certificate = System.Security.Cryptography.X509Certificates.X509Certificate;
using Newtonsoft.Json;
using Path = System.IO.Path;
using BLL.User;
using DIT.Utilities;
using Models.User;
using BLL.Admission;
using BLL.Common;


//using Microsoft.Office.Interop.Word;

namespace DIT.Controllers
{


    public class NotificationController : Controller
    {

        private readonly INotificationBLL _NotifBll;
        private readonly IMarksBLL _marksBll;

        private readonly IUserBLL _LoginService;
        private readonly IAdmissionBLL _admissionBll;
        private readonly ICommonBLL _CommonBLL;

        private readonly string UploadFolder = ConfigurationManager.AppSettings["TemplateDocumentsPath"];
        private readonly string UploadWordFolder = ConfigurationManager.AppSettings["WordTemplateDocumentsPath"];

        //BNM Question Paper Upload
        private readonly string UploadFolderQP = ConfigurationManager.AppSettings["QPDocumentsPath"];

        // strings to be replaced in template
        private readonly string ReplaceNoticeNumberKannada = "&lt;ಅಧಿಸೂಚನೆ ಸಂ.&gt;";
        private readonly string ReplaceNoticeDateKannada = "&lt;ಅಧಿಸೂಚನೆ ದಿನಾಂಕ&gt;";
        private readonly string ReplaceFeesLastDateKannada = "&lt;ಕೊನೆಯ ದಿನಾಂಕ&gt;";

        private readonly string ReplaceNoticeNumberEnglish = "&lt;Notification Number&gt;";
        private readonly string ReplaceNoticeDateEnglish = "&lt;Notification Date&gt;";
        private readonly string ReplaceFeesLastDateEnglish = "&lt;Last Date&gt;";
        private readonly string ReplaceDescription = "&lt;Description&gt;";

        // strings to generate file name
        private readonly string PdfFileNameFormat = "Notification_{0}.pdf";
        private readonly string DocFileNameFormat = "Notification_{0}.docx"; //changed docx to doc
        private readonly string HTMLFilename = "Notification_{0}.html";


        // function to replace the strings
        private string ReplaceDataInTemplate(string content, Notification model, bool onlyNofificationDate = false)
        {
            if(onlyNofificationDate)
            {
                DateTime dateTime = DateTime.Now;
                string notificationDate = string.Format("{0:D2}/{1:D2}/{2}", dateTime.Day, dateTime.Month, dateTime.Year);
                content = content.Replace(ReplaceNoticeDateKannada, notificationDate);
                content = content.Replace(ReplaceNoticeDateEnglish, notificationDate);
            }
            else
            {
                content = content.Replace(ReplaceNoticeDateKannada, model.Exam_notif_date.ToString("dd:MM:yyyy"));
                content = content.Replace(ReplaceNoticeNumberKannada, model.Exam_Notif_Number);
                content = content.Replace(ReplaceFeesLastDateKannada, ((DateTime)model.fee_pay_last_date).ToString("dd:MM:yyyy"));

                content = content.Replace(ReplaceNoticeDateEnglish, model.Exam_notif_date.ToString("dd:MM:yyyy"));
                content = content.Replace(ReplaceNoticeNumberEnglish, model.Exam_Notif_Number);
                content = content.Replace(ReplaceFeesLastDateEnglish, ((DateTime)model.fee_pay_last_date).ToString("dd:MM:yyyy"));
            }

            return content;
        }
        public NotificationController()
        {
            _marksBll = new MarksBLL();
            _NotifBll = new NotificationBLL();
            this._LoginService = new UserBLL();
            _admissionBll = new AdmissionBLL();
            _CommonBLL = new CommonBLL();
        }

        // GET: Notification
        public ActionResult Index()
        {
      CheckBrowserAndMenuUl();
      return View();
        }

        /// <summary>
        /// get action method for creating notification
        /// </summary>
        /// <param name="notificationId">holds the notification id for updating notifcation, otherwise it will be null</param>
        /// <returns></returns>
        public ActionResult CreateNotification(int? notificationId, int? selectedTab)
        {
            //CheckBrowserAndMenuUl();
            _CommonBLL.CheckBrowserAndMenuUlBLL(Convert.ToString(Session["UserId"]), Convert.ToString(Session["MenuMappingId"]), Convert.ToString(Session["CurrentPage"]), Convert.ToString(Session["UserName"]), Convert.ToString(Session["sessionid"]), Request, Response, Session);
            
            // create model object  
            Notification model = new Notification();
            int loginId = Convert.ToInt32(Session["LoginId"]);
            int userId = Convert.ToInt32(Session["UserId"]);
            string content = string.Empty;
            model.Exam_notif_date = DateTime.Now;
            model.fee_pay_last_date= DateTime.Now;
            //Kannada template
            //content = "<p style=\"text-align: center; font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Tunga',sans-serif;\">ಕರ್ನಾಟಕ ಸರ್ಕಾರ </p><p style=\"font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Tunga',sans-serif;\">ದಿನಾಂಕ : &lt;ಅಧಿಸೂಚನೆ ದಿನಾಂಕ&gt;</p><p style=\"text-align: right; font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Tunga',sans-serif;\">ಅಧಿಸೂಚನೆ ಸಂ.: &lt;ಅಧಿಸೂಚನೆ ಸಂ.&gt;</p><p>&nbsp;</p><p style=\"text-align: center;font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 107%; font-family: 'Tunga',sans-serif;\">ಅಧಿಸೂಚನೆ</p><br>";
            content = "<h2 style=\"text-align: center;\"><span style=\"font-family: 'times new roman', times, serif;\">Government of Karnataka</span></h2>\r\n<p>&nbsp;</p>\r\n<p class=\"MsoNormal\" style=\"margin-bottom: 0cm; line-height: normal; mso-layout-grid-align: none; text-autospace: none;\"><span style=\"font-size: 12pt; font-family: 'times new roman', times, serif;\">&lt;Notification Number&gt;</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: right; line-height: 1;\" align=\"right\"><span style=\"font-family: 'times new roman', times, serif;\">Industrial training and employment</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: right; line-height: 1;\" align=\"right\"><span style=\"font-family: 'times new roman', times, serif;\">Skill House, Dairy Circle,</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: right; line-height: 1;\" align=\"right\"><span style=\"font-family: 'times new roman', times, serif;\">Bannerghatta Road, Bangalore-560 029,</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: right; line-height: 1;\" align=\"right\"><span style=\"font-family: 'times new roman', times, serif;\">Date: &lt;Notification Date&gt;</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: center;\" align=\"center\"><span style=\"font-family: 'times new roman', times, serif;\">NOTIFICATION</span></p>\r\n<p class=\"MsoNormal\" style=\"text-align: center;\" align=\"center\"><span style=\"font-family: 'times new roman', times, serif;\">Topic:&lt;Description&gt;</span></p>";
           // content = "<p style=\"text-align: center; \">Government of Karnataka</p><p>Notification Date: &lt;Notification Date&gt;</p><p style=\"text-align: right;\">Notification Number : &lt;Notification Number&gt;</p><p>&nbsp;</p><p style=\"text-align: center;\">NOTIFICATION</p><br>";

            if (notificationId != null)
            {
                model = _NotifBll.GetUpdateNotificationBLL(notificationId)[0];
                string DocumentsFolder = GetUploadFolderPath(); 
                //Replace the Notification number slash by hipen
                string fileName = model.Exam_Notif_Number.Replace(@"/", "_");
                string wordpath = string.Format(DocumentsFolder + DocFileNameFormat, fileName);
                content = ReadWordFile(wordpath);
                // replace the template date and notification number
                //content = ReplaceDataInTemplate(content, model);
            }
            else
            {
                content = ReplaceDataInTemplate(content, model,true);
            }
            model.content = content;
            //read the notification detail dropdowns
            model.DeptId = 1;
            model.NotifDescId = 1;
            model.CourseList = _NotifBll.GetCourseListBLL();
            model.DeptList = _NotifBll.GetDepartmentListBLL();
            model.NotifDescList = _NotifBll.GetNotificationDescListBLL();

            //read last notification id
            model.LastNotigicationId = _NotifBll.LastNotificationNumberBLL(model);
            foreach (var department in model.DeptList)
            {
                if (department.Value == model.DeptId.ToString())
                {
                    model.DeptName = department.Text;
                    break;
                }
            }
            foreach (var notificationDescription in model.NotifDescList)

DIT/Views/Notification/ExamTemplateFormat.cshtml
@model Models.ExamNotification.Notification
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExamTemplateFormat</title>
    <style>
        #child-left {
            float: right;
            width: 300px;
        }
        
        .mceEditor {
            
            /*height: 500px;*/
           /*// width:700px;*/
        }
         .tox{
           /*// width: 1000px;*/
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    @*<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>*@
    @*<script type="text/javascript" src="~/Scripts/tinymce.min.js"></script>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.6.2/tinymce.min.js" integrity="sha512-sOO7yng64iQzv/uLE8sCEhca7yet+D6vPGDEdXCqit1elBUAJD1jYIYqz0ov9HMd/k30e4UVFAovmSG92E995A==" crossorigin="anonymous"></script>

    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea',
            width: 1520,
            height: 300
            
        });
    </script>

</head>


@*<body>
        <div>

            <div class="Container">
                <h5 style="text-align:center">Karnatak Government</h5>
                <div class="row">
                    <div class="col-lg-4">
                        @ViewBag.NotificationNumber
                    </div>
                    <div class="col-lg-4" id="child-left">
                        <pre>
    Industrial training and employment
    Skill House, Dairy Circle,
    Bannerghatta Road, Bangalore-560 029,
    Date: @ViewBag.NotificationDate

    </pre>
                    </div>
                </div>
            </div>
            <br /><br /><br />
            <div class="Container">
                <h5 style="text-align:center">NOTIFICATION </h5>
                <p>
                    Topic: -August 2019 under Artisan Training Program
                    About the state career test (SCVT)
                </p>
                <p>*************</p>
                <p>
                    With respect to the above, apply for the state career exam to be held in August 2019 The notification is issued by setting the date for filing and payment of fixed fees. To act accordingly
                </p>
                <p>
                    1) Regular / Repeater of Government and Private Industrial Training Institute Trainees Examination Fees without Penalties at Government Industrial Training Institutes concerned Deadline to pay: @ViewBag.NotificationDate
                </p>
                <p>2) Regular of Government and Private Industrial Training Institute Failure (Repeater) Industrial related to test applications filled out by trainees Deadline for submission at training institutes.@ViewBag.NotificationDate</p>
                <p>3) SSLC applications for trainees from government and private industrial training institutes Name of the trainee as well as the father's name and birth as in the list Check the date, composition and a copy of the approved entry list (Private Industrial Training Institutes) with CD and Hard copy Last date for submission of checklist to the concerned test center is @ViewBag.NotificationDate</p>
                <p>4) Examination center review all applications, to the divisional office Deadline to submit: 18/07/2019 Applications of each Industrial Training Institute are regular and failing Candidates (composition, approved entry list) are correct with these Check, list separately the proposals to the Divisional Office with the CD Sending mandatory time. Receipt of payment of test fee Confirmation of Attachment of Application</p>
                <p>5) Joint Director, Divisional Office, Government / Private within their jurisdiction Check the composition of industrial training institutes, correct Application forms with information and hard copy And a copy of the approved list to the test headquarters Deadline to send: @ViewBag.NotificationDate</p>
            </div>




        </div>
    </body>*@
<body>

    @using (Html.BeginForm("ExamTemplateFormat", "Notification", FormMethod.Post, new { id = "formText" }))
    {
        <div>
            @*<textarea id="txtarea"></textarea>*@
            @Html.TextAreaFor(m => m.content, new { @class = "mceEditor" })
            <br />
            <input type="button" id="btnValue" value="PreView" />
            <input type="submit" id="createNotification1" value="Create" class="btn btn-success" style="margin-left:15px;" />

            <div id="divkarea"></div>
        </div>
    }

    @*<div>
        <textarea id="txtarea"></textarea>
        <br/>
        <input type="button" id="btnValue" value="PreView" />   <input type="button" id="createNotification" value="Create" class="btn btn-success" style="margin-left:15px;" />

        <div id="divkarea"></div>*@
</body>
</html>
<script>
    $(document).ready(function () {
        $('#btnValue').click(function () {
            $("#divkarea").html("");
            debugger;
            //var content = tinymce.get("txtarea").getContent();
            var content = tinymce.get("content").getContent();
            $("#divkarea").html(content);
        });
    });


</script>





@*<script>
           var rteObj;
           debugger;
        $(function () {
            $("#createNotification").on("click", function () {
                 rteObj = tinymce.get("txtarea").getContent();
                $.ajax({
                    url: "@Url.Action("ExamTemplateFormat", "Notification") ' + '?content=' content",
                    type: "post",
                    contentType: "application/json; charset=utf-8",
                    success: function (e) {
                        rteObj.setHtml(e); //setting Html content for RTE
                    }
                });
            });
        });
        function onCreate() {
            rteObj = this; // accessing control’s instance
        }
    </script>*@

@*<script>
    //$("#createNotification").click(function () {
    //    var content = tinymce.get("txtarea").getContent();
    //    debugger;
    //    alert("button");
    //    $.ajax({
    //        type: "Post",
    //        url: "/Notification/ExamTemplateFormat",
    //        contentType: 'application/json; charset=utf-8',
    //        data: { content: content },
    //        success: function (html) {

    //            if (data == true) {
    //                alert("value");
    //            }
    //            else {
    //                alert("Value Not");
    //            }
    //        }
    //    });
    //});
</script>*@

DIT/Views/Notification/RegisterDSCDetails.cshtml
@model Models.ExamNotification.DSCModel

@{
    ViewBag.Title = "RegisterDSCDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/DigitalSignCerti.min.js"></script>
<script>
    $(document).ready(function () {
        $("#Save").hide();

        $("#DSCUpdation").click(function (e) {
            e.preventDefault();
        });
    });

    function SignInWithDSCLogin(e) {
        debugger;
        //e.preventDefault();
        if (!isBrowserSupportsExtension() || !isExtensionInstalled()) {
            $("#errLogin").html("Please Download Chrome Extension.");
            return;
        }
        DSCSignRegSignedExtension.getSelectedCertificate()
            .then(
                function (CertInfo) {
                    var jobj = JSON.parse(CertInfo);
                    var SelCertSubj = jobj.SelCertSubject.split(',');

                    $("#DSCName").val(SelCertSubj[0].split('=')[1]);
                    $("#SerialNo").val(SelCertSubj[1].split('=')[1]);
                    $("#Place").val(SelCertSubj[2].split('=')[1]);
                    $("#PhoneNumber").val(SelCertSubj[4].split('=')[1]);
                    $("#ExpiryDate").val(jobj.ExpDate);
                    $("#PublicKey").val(jobj.PublicKey);
                    $("#ValidFromDate").val(jobj.ValidFrom);
                    $("#issuerEmail").val(jobj.eMail);
                    $("#certifyingAuthority").val(jobj.issuerName.Name.split(',')[2].split('=')[1]);
                    $("#createuser").show();
                    $("#DSCUpdation").hide();

                    $("#Save").show();
                },
                function (errmsg) {
                    $("#ResultDisplay").html(errmsg.message);
                    $("#Save").hide();
                }
            );
    }

</script>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                        @*<div class="breadcrumb font">
                                <span class="inline odd first"><a href="/Home/index1">Home</a></span> <span class="delimiter">&gt;</span>  <span class="inline odd last">
                                    Notification Status
                                </span>

                            </div>*@
                        <li class="breadcrumb-item"><a href="/Home/index1">Home</a></li>
                        <li class="breadcrumb-item active">Register DSC Key</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Details Of Work</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                @using (Html.BeginForm("RegisterDSCDetails", "Notification", FormMethod.Post, new { @id = "structure" }))
                {
                    @Html.AntiForgeryToken();
                    <div class="card-body">
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        @if (ViewBag.Status != null && ViewBag.Status == "Success")
                        {
                            <h4 class="text-success">DSC Key Registered Successfully</h4>
                        }
                        else if (ViewBag.Status != null && ViewBag.Status == "Failed")
                        {
                            <h4>Failed to Insert.</h4>
                        }
                        @if (ViewBag.Status != "Success")
                        {
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">DSC Name<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.DSCName, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Place<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.Place, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Issuer Email<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.issuerEmail, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Serial No<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.SerialNo, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Expiry Date<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.ExpiryDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">ValidFromDate<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.ValidFromDate, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Certifying Authority<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(Model => Model.certifyingAuthority, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    @Html.HiddenFor(Model => Model.PhoneNumber)
                                    <div class="col-md-6">
                                        <label for="txtAgencyRegnNo">Public Key<span style="color:red">*</span></label>
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextAreaFor(Model => Model.PublicKey, new { @class = "form-control", @readonly = "readonly" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        @if (ViewBag.Status != "Success")
                        {
                            <div class="row">
                                <div class="col-md-7">
                                </div>
                                <div class="col-md-1">
                                    <input type="button" id="DSCUpdation" value="Link DSC Key" class="btn btn-info" style="margin-left:15px" onclick="SignInWithDSCLogin();" />
                                </div>
                                <div class="col-md-1">
                                    <button type="submit" name="submit" class="btn btn-primary" id="Save" value="Save" style="float:right">&nbsp;Save&nbsp;</button>
                                </div>
                                <div class="col-md-1">
                                    @*<button type="submit" name="submit" class="btn btn-info" id="Sign" value="Sign" style="float:right">&nbsp;&nbsp;Sign&nbsp;&nbsp;</button>*@
                                </div>
                                <div class="col-md-2">
                                    @*<button type="submit" name="submit" class="btn btn-success" id="Generate Work ID" value="Generate Work ID" style="float:right">Generate Work ID</button>*@
                                </div>
                            </div>
                        }
                    </div>
                    <!-- Large modal -->
                    <button type="button" class="btn btn-primary" id="errorbutton" style="display:none" data-toggle="modal" data-target=".modal">Large modal</button>

                    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                                <div class="modal-body" id="ErrorMSG">
                                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                }
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>




@*@section scripts {

    }*@